baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "NRtheme"

[[menu.main]]
  name = "link to home"
  title = "home section"
  weight = 1
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "link to docs"
  title = "documentation"
  weight = 1
  identifier = "docs"
  url = "/documentation/"

[[menu.main]]
  name = "link to about"
  title = "about"
  weight = 1
  identifier = "about"
  url = "/about/"
